use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

target 'wow-util_Example' do
  pod 'wow-util', :path => '../'

  target 'wow-util_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
