use_frameworks!
platform :ios, '9.0'
source 'http://github.com/gakaki/wowdsgn_podspec.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'wow-ui_Example' do
  pod 'wow-ui', :path => '../'


end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0.0'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
