use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!



target 'wow-model-network_Example' do
  pod 'wow-model-network', :path => '../'
  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
